export const questions = [
  { id: 1, text: 'Was macht dich glücklich?', createdBy: 'system' },
  { id: 2, text: 'Was ist dein Lieblingsessen?', createdBy: 'system' },
  { id: 3, text: 'Welches Land möchtest du besuchen?', createdBy: 'system' },
  { id: 4, text: 'Was ist dein grösstes Hobby?', createdBy: 'system' },
  { id: 5, text: 'Was war dein schönstes Geschenk?', createdBy: 'system' },
  { id: 6, text: 'Welche Superkraft hättest du gerne?', createdBy: 'system' },
  { id: 7, text: 'Was kannst du besonders gut?', createdBy: 'system' },
  { id: 8, text: 'Was wolltest du als Kind werden?', createdBy: 'system' },
  { id: 9, text: 'Was ist dir bei Freundschaften wichtig?', createdBy: 'system' },
  { id: 10, text: 'Worüber kannst du stundenlang reden?', createdBy: 'system' },
  { id: 11, text: 'Was ist dein Lieblingsfilm oder deine Lieblingsserie?', createdBy: 'system' },
  { id: 12, text: 'Wenn du eine Zeitreise machen könntest – wohin?', createdBy: 'system' },
  { id: 13, text: 'Was ist dein Morgenritual?', createdBy: 'system' },
  { id: 14, text: 'Welche Musik hörst du am liebsten?', createdBy: 'system' },
  { id: 15, text: 'Was steht auf deiner Bucket List?', createdBy: 'system' },
  { id: 16, text: 'Was bringt dich zum Lachen?', createdBy: 'system' },
  { id: 17, text: 'Hast du ein verstecktes Talent?', createdBy: 'system' },
  { id: 18, text: 'Was würdest du mit 1 Million Franken machen?', createdBy: 'system' },
  { id: 19, text: 'Was ist dein Lieblingsort in der Schweiz?', createdBy: 'system' },
  { id: 20, text: 'Welches Tier beschreibt dich am besten?', createdBy: 'system' },
]
